(()=>{var c=(o,u,e)=>new Promise((t,s)=>{var n=i=>{try{a(e.next(i))}catch(r){s(r)}},l=i=>{try{a(e.throw(i))}catch(r){s(r)}},a=i=>i.done?t(i.value):Promise.resolve(i.value).then(n,l);a((e=e.apply(o,u)).next())});(function(){class o{constructor(){this.isOpen=!1;this.keysPressed={};this.onResults=e=>{setTimeout(()=>{this.autoCompleteJS.goTo(0)})};this.onSelection=e=>{let s=e.detail.selection.value;typeof s.url=="string"&&(this.trackSelection(s.url),this.go(s.url))};this.getData=()=>c(this,null,function*(){try{let e=this.$element.dataset.cacheId,t=localStorage?JSON.parse(localStorage.getItem("valetData")):null;if(localStorage&&t!==null){let s=localStorage.getItem("valetCacheId");e!==s&&(localStorage.setItem("valetCacheId",e),t=null)}return t===null?yield this.fetchData().then(n=>{let l=JSON.stringify(n);return l!==JSON.stringify({})&&localStorage.setItem("valetData",l),n}):t}catch(e){return e}});this.fetchData=()=>c(null,null,function*(){try{return yield(yield fetch(drupalSettings.path.baseUrl+"api/valet")).json()}catch(e){return e}});this.isEditableElement=e=>e instanceof HTMLElement&&e.isContentEditable?!0:e instanceof HTMLInputElement&&/|text|email|number|password|search|tel|url/.test(e.type||"")||e instanceof HTMLTextAreaElement?!(e.disabled||e.readOnly):!1;this.$element=document.getElementById("valet"),this.$input=document.getElementById("valet--input"),this.$close=document.getElementById("valet--close"),this.bind(),this.build()}bind(){document.addEventListener("keydown",e=>{this.keysPressed[e.key]=!0,this.keysPressed.Shift&&this.keysPressed[" "]&&(this.isEditableElement(document.activeElement)||(e.preventDefault(),this.open())),this.isOpen===!0&&this.keysPressed.Escape&&(e.preventDefault(),this.close())}),document.addEventListener("keyup",e=>{delete this.keysPressed[e.key]}),this.$element.addEventListener("click",e=>{e.preventDefault(),e.target===this.$element&&this.close()}),this.$close.addEventListener("click",e=>{e.preventDefault(),this.close()})}build(){this.autoCompleteJS=new autoComplete({selector:"#valet--input",data:{src:this.getData,cache:!0,filter:e=>{let t=this.getSelectionHistory();return e.filter((s,n,l)=>l.findIndex(a=>a.value.url===s.value.url)===n).sort((s,n)=>{let l=s.key==="label"?1:0,a=n.key==="label"?1:0;if(l!==a)return a-l;let i=t[s.value.url]||0;return(t[n.value.url]||0)-i})},keys:["label","tags"]},threshold:1,debounce:50,resultsList:{element:(e,t)=>{let s=document.createElement("p");s.classList.add("overview"),t.results.length>0?s.innerHTML=`Displaying <strong>${t.results.length}</strong> out of <strong>${t.matches.length}</strong> results`:s.innerHTML=`Found <strong>${t.matches.length}</strong> matching results for <strong>"${t.query}"</strong>`,e.append(s)},noResults:!0,maxResults:6,tabSelect:!0},resultItem:{element:(e,t)=>{e.id==="autoComplete_result_0"&&e.setAttribute("aria-selected",!0),e.innerHTML=`
            <span class="title">
              <span class="icon ${t.value.icon}"></span>
              ${t.value.label}
            </span>
            <span class="description">
              ${t.value.description}
            </span>
            <span class="url">
              ${t.value.url.split("?")[0]}
            </span>`},highlight:!0}}),this.autoCompleteJS.input.addEventListener("results",this.onResults),this.autoCompleteJS.input.addEventListener("selection",this.onSelection)}getSelectionHistory(){try{return JSON.parse(localStorage.getItem("valetHistory"))||{}}catch(e){return{}}}trackSelection(e){let t=this.getSelectionHistory();t[e]=(t[e]||0)+1,localStorage.setItem("valetHistory",JSON.stringify(t))}go(e){e=e.replace("RETURN_URL",window.location.pathname.substring(1)),this.keysPressed.Meta?(this.close(),window.open(e)):(this.$input.setAttribute("placeholder","Please wait..."),this.$input.value="",this.$input.disabled=!0,window.location=e)}open(){this.keysPressed={},this.isOpen=!0,this.$element.classList.add("valet--active"),this.$input.value="",setTimeout(()=>{this.$input.focus()},300)}close(){this.isOpen=!1,this.$element.classList.remove("valet--active")}}new o})();})();
//# sourceMappingURL=valet.js.map
