(()=>{var c=(o,p,e)=>new Promise((t,l)=>{var a=s=>{try{n(e.next(s))}catch(r){l(r)}},i=s=>{try{n(e.throw(s))}catch(r){l(r)}},n=s=>s.done?t(s.value):Promise.resolve(s.value).then(a,i);n((e=e.apply(o,p)).next())});(function(){class o{constructor(){this.isOpen=!1;this.keysPressed={};this.popularIndex=-1;this.onResults=e=>{setTimeout(()=>{this.autoCompleteJS.goTo(0)})};this.onSelection=e=>{let l=e.detail.selection.value;typeof l.url=="string"&&(this.trackSelection(l.url),this.go(l.url))};this.getData=()=>c(this,null,function*(){try{let e=this.$element.dataset.cacheId,t=localStorage?JSON.parse(localStorage.getItem("valetData")):null;if(localStorage&&t!==null){let l=localStorage.getItem("valetCacheId");e!==l&&(localStorage.setItem("valetCacheId",e),t=null)}return t===null?yield this.fetchData().then(a=>{let i=JSON.stringify(a);return i!==JSON.stringify({})&&localStorage.setItem("valetData",i),a}):t}catch(e){return e}});this.fetchData=()=>c(null,null,function*(){try{return yield(yield fetch(drupalSettings.path.baseUrl+"api/valet")).json()}catch(e){return e}});this.isEditableElement=e=>e instanceof HTMLElement&&e.isContentEditable?!0:e instanceof HTMLInputElement&&/|text|email|number|password|search|tel|url/.test(e.type||"")||e instanceof HTMLTextAreaElement?!(e.disabled||e.readOnly):!1;this.$element=document.getElementById("valet"),this.$input=document.getElementById("valet--input"),this.$close=document.getElementById("valet--close"),this.$popular=this.buildPopular(),this.bind(),this.build()}buildPopular(){let e=document.createElement("div");return e.className="valet--popular",e.style.display="none",this.$element.querySelector(".valet--form").appendChild(e),e}showPopular(){let e=this.getSelectionHistory(),t=Object.keys(e);if(t.length===0){this.$popular.style.display="none";return}let l=t.map(s=>({url:s,count:e[s]})).sort((s,r)=>r.count-s.count).slice(0,5),a=[];try{a=JSON.parse(localStorage.getItem("valetData"))||[]}catch(s){}let i={};Array.isArray(a)&&a.forEach(s=>{s.url&&(i[s.url]=s)});let n=l.map(s=>i[s.url]).filter(Boolean);if(n.length===0){this.$popular.style.display="none";return}this.$popular.innerHTML='<div class="valet--popular-label">Recent</div>'+n.map(s=>`
          <a class="valet--popular-item" href="${s.url}" data-url="${s.url}">
            <span class="icon ${s.icon||""}"></span>
            <span class="label">${s.label}</span>
          </a>
        `).join(""),this.$popular.style.display="",this.popularIndex=-1,this.$popular.querySelectorAll(".valet--popular-item").forEach(s=>{s.addEventListener("click",r=>{r.preventDefault();let u=s.dataset.url;u&&(this.trackSelection(u),this.go(u))})})}hidePopular(){this.$popular.style.display="none",this.popularIndex=-1,this.updatePopularSelection()}isPopularVisible(){return this.$popular.style.display!=="none"}getPopularItems(){return this.$popular.querySelectorAll(".valet--popular-item")}updatePopularSelection(){this.getPopularItems().forEach((t,l)=>{l===this.popularIndex?t.classList.add("is-active"):t.classList.remove("is-active")})}handlePopularKeydown(e){if(!this.isPopularVisible())return!1;let t=this.getPopularItems();if(t.length===0)return!1;if(e.key==="ArrowDown")return e.preventDefault(),this.popularIndex=Math.min(this.popularIndex+1,t.length-1),this.updatePopularSelection(),!0;if(e.key==="ArrowUp")return e.preventDefault(),this.popularIndex=Math.max(this.popularIndex-1,-1),this.updatePopularSelection(),!0;if(e.key==="Enter"&&this.popularIndex>=0){e.preventDefault();let a=t[this.popularIndex].dataset.url;return a&&(this.trackSelection(a),this.go(a)),!0}return!1}bind(){document.addEventListener("keydown",e=>{this.keysPressed[e.key]=!0,this.keysPressed.Shift&&this.keysPressed[" "]&&(this.isEditableElement(document.activeElement)||(e.preventDefault(),this.open())),this.isOpen===!0&&this.keysPressed.Escape&&(e.preventDefault(),this.close()),this.isOpen&&this.handlePopularKeydown(e)}),document.addEventListener("keyup",e=>{delete this.keysPressed[e.key]}),this.$element.addEventListener("click",e=>{e.preventDefault(),e.target===this.$element&&this.close()}),this.$close.addEventListener("click",e=>{e.preventDefault(),this.close()}),window.addEventListener("pageshow",e=>{e.persisted&&this.close()}),this.$input.addEventListener("input",()=>{this.$input.value.length>0?this.hidePopular():this.showPopular()})}build(){this.autoCompleteJS=new autoComplete({selector:"#valet--input",data:{src:this.getData,cache:!0,filter:e=>{let t=this.getSelectionHistory();return e.filter((l,a,i)=>i.findIndex(n=>n.value.url===l.value.url)===a).sort((l,a)=>{let i=l.key==="label"?1:0,n=a.key==="label"?1:0;if(i!==n)return n-i;let s=t[l.value.url]||0;return(t[a.value.url]||0)-s})},keys:["label","tags"]},threshold:1,debounce:50,resultsList:{element:(e,t)=>{let l=document.createElement("p");l.classList.add("overview"),t.results.length>0?l.innerHTML=`Displaying <strong>${t.results.length}</strong> out of <strong>${t.matches.length}</strong> results`:l.innerHTML=`Found <strong>${t.matches.length}</strong> matching results for <strong>"${t.query}"</strong>`,e.append(l)},noResults:!0,maxResults:6,tabSelect:!0},resultItem:{element:(e,t)=>{e.id==="autoComplete_result_0"&&e.setAttribute("aria-selected",!0),e.innerHTML=`
            <span class="title">
              <span class="icon ${t.value.icon}"></span>
              ${t.value.label}
            </span>
            <span class="description">
              ${t.value.description}
            </span>
            <span class="url">
              ${t.value.url.split("?")[0]}
            </span>`},highlight:!0}}),this.autoCompleteJS.input.addEventListener("results",this.onResults),this.autoCompleteJS.input.addEventListener("selection",this.onSelection)}getSelectionHistory(){try{return JSON.parse(localStorage.getItem("valetHistory"))||{}}catch(e){return{}}}trackSelection(e){let t=this.getSelectionHistory();t[e]=(t[e]||0)+1,localStorage.setItem("valetHistory",JSON.stringify(t))}go(e){e=e.replace("RETURN_URL",window.location.pathname.substring(1)),this.keysPressed.Meta?(this.close(),window.open(e)):(this.$input.setAttribute("placeholder","Please wait..."),this.$input.value="",this.$input.disabled=!0,window.location=e)}open(){this.keysPressed={},this.isOpen=!0,this.$element.classList.add("valet--active"),this.$input.value="",this.showPopular(),setTimeout(()=>{this.$input.focus()},300)}close(){this.isOpen=!1,this.$element.classList.remove("valet--active"),this.$input.value="",this.$input.disabled=!1,this.$input.setAttribute("placeholder","Search...")}}new o})();})();
//# sourceMappingURL=valet.js.map
